### ISSUE TITLE
Don't use axios

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [SuspiciousLookingOwl/saweria-api#3]
`axios` is probably overkill for this library. I'm going to switch the HTTP Client, probably to native `https` module to make this library dependency-free.

**Comment by kelvin-junilson** [comment]
idk if this is related but somehow there's this error right now when trying to login into SaweriaClient


```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (_http_outgoing.js:536:3)
    at new ClientRequest (_http_client.js:249:14)
    at Object.request (https.js:310:10)
    at RedirectableRequest._performRequest (G:\Minecraft\minecraft-donate\node_modules\follow-redirects\index.js:265:24)
    at new RedirectableRequest (G:\Minecraft\minecraft-donate\node_modules\follow-redirects\index.js:61:8)
    at Object.request (G:\Minecraft\minecraft-donate\node_modules\follow-redirects\index.js:456:14)
    at dispatchHttpRequest (G:\Minecraft\minecraft-donate\node_modules\axios\lib\adapters\http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (G:\Minecraft\minecraft-donate\node_modules\axios\lib\adapters\http.js:21:10)
    at dispatchRequest (G:\Minecraft\minecraft-donate\node_modules\axios\lib\core\dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
} 
```

any clue why this happens?

**Comment by SuspiciousLookingOwl** [comment]
Can you share your minimal reproducible code?

**Comment by kelvin-junilson** [comment]
Please disregard, I forgot to set the password and email to my env. Apologies
